# Comparison all models from the separate 2 notebooks

In [1]:
import pandas as pd

In [51]:
dict = {'0': "O",
'1': 'addName',
'2': 'bloc',
'3': 'country',
'4': 'date',
'5': 'district',
'6': 'forename',
'7': 'geogName',
'8': 'orgName',
'9': 'persName',
'10': 'placeName',
'11': 'region',
'12': 'settlement',
'13': 'surname',
'14': 'time',
  'micro avg':'micro avg',
       'macro avg':'macro avg',
     'weighted avg': 'weighted avg' ,
       'samples avg':'samples avg'}

In [52]:
CRF_final_valid = pd.read_csv('/home/jan.solarz/Pobrane/Jan Solarz- Projects/INL/report_valid_cff_2.csv')

In [54]:
p = []
for i in CRF_final_valid['Unnamed: 0']:
    p.append(dict[str(i)])

In [55]:
CDT = pd.read_csv('/home/jan.solarz/Pobrane/Jan Solarz- Projects/INL/report_tree_all.csv')

In [56]:
def report_df(data):  
    
    data.rename(columns = {'Unnamed: 0':'tag'}, inplace = True)
    data['tag'] = p
    return data

In [58]:
CDT

             tag  precision    recall  f1-score        support
0              O   0.944350  0.997635  0.970261  655825.000000
1        addName   0.000000  0.000000  0.000000     568.000000
2           bloc   0.000000  0.000000  0.000000      88.000000
3        country   0.000000  0.000000  0.000000    4934.000000
4           date   0.536266  0.332106  0.410186    2716.000000
5       district   0.000000  0.000000  0.000000     176.000000
6       forename   0.000000  0.000000  0.000000    8304.000000
7       geogName   0.000000  0.000000  0.000000    2629.000000
8        orgName   0.584844  0.227504  0.327579    7090.000000
9       persName   0.000000  0.000000  0.000000     699.000000
10     placeName   0.000000  0.000000  0.000000     217.000000
11        region   0.000000  0.000000  0.000000     486.000000
12    settlement   0.333333  0.000401  0.000801    4985.000000
13       surname   0.136364  0.000726  0.001444    8268.000000
14          time   0.000000  0.000000  0.000000     350.000000
15      accuracy   0.941867  0.941867  0.941867       0.941867
16     macro avg   0.169010  0.103891  0.114018  697335.000000
17  weighted avg   0.900171  0.941867  0.917456  697335.000000

In [59]:
CRF_1_train = pd.read_csv('/home/jan.solarz/Pobrane/Jan Solarz- Projects/INL/report_train_cff.csv')

## CRF_1

In [60]:
report_df(CRF_1_train)

             tag  precision    recall  f1-score  support
0              O   0.999885  1.000000  0.999943  43520.0
1        addName   0.990291  0.983923  0.987097    311.0
2           bloc   0.953488  0.854167  0.901099     48.0
3        country   0.991162  0.997459  0.994300   2361.0
4           date   0.987543  0.974727  0.981093   1464.0
5       district   1.000000  0.990291  0.995122    103.0
6       forename   0.978641  0.996068  0.987278   4324.0
7       geogName   0.986122  0.968939  0.977455   1320.0
8        orgName   0.981845  0.971151  0.976469   3397.0
9       persName   0.990244  0.975962  0.983051    416.0
10     placeName   1.000000  1.000000  1.000000    120.0
11        region   1.000000  0.992095  0.996032    253.0
12    settlement   0.998031  0.999211  0.998621   2536.0
13       surname   0.996208  0.985694  0.990923   4264.0
14          time   0.960976  0.920561  0.940334    214.0
15     micro avg   0.996053  0.995298  0.995675  64651.0
16     macro avg   0.987629  0.974017  0.980588  64651.0
17  weighted avg   0.996051  0.995298  0.995659  64651.0
18   samples avg   0.997310  0.996746  0.996514  64651.0

In [61]:
CRF_1_valid = pd.read_csv('/home/jan.solarz/Pobrane/Jan Solarz- Projects/INL/report_valid_cff.csv')

In [62]:

report_df(CRF_1_valid)

             tag  precision    recall  f1-score  support
0              O   0.999502  0.999962  0.999732  26103.0
1        addName   0.643836  0.236181  0.345588    199.0
2           bloc   0.428571  0.193548  0.266667     31.0
3        country   0.923710  0.859429  0.890411   1437.0
4           date   0.924731  0.866741  0.894798    893.0
5       district   0.727273  0.135593  0.228571     59.0
6       forename   0.870515  0.866123  0.868314   2577.0
7       geogName   0.768959  0.509346  0.612790    856.0
8        orgName   0.814566  0.718025  0.763255   2025.0
9       persName   0.894180  0.695473  0.782407    243.0
10     placeName   0.931818  0.546667  0.689076     75.0
11        region   0.871795  0.441558  0.586207    154.0
12    settlement   0.838323  0.762943  0.798859   1468.0
13       surname   0.862351  0.848790  0.855517   2480.0
14          time   0.758242  0.610619  0.676471    113.0
15     micro avg   0.956886  0.926459  0.941427  38713.0
16     macro avg   0.817225  0.619400  0.683911  38713.0
17  weighted avg   0.952004  0.926459  0.937045  38713.0
18   samples avg   0.975445  0.956299  0.959837  38713.0

In [63]:
CRF_final_valid = pd.read_csv('/home/jan.solarz/Pobrane/Jan Solarz- Projects/INL/report_valid_cff_2.csv')

In [64]:

report_df(CRF_final_valid)

             tag  precision    recall  f1-score  support
0              O   0.999808  1.000000  0.999904  26103.0
1        addName   0.994898  0.979899  0.987342    199.0
2           bloc   1.000000  0.838710  0.912281     31.0
3        country   0.993767  0.998608  0.996182   1437.0
4           date   0.990930  0.978723  0.984789    893.0
5       district   1.000000  1.000000  1.000000     59.0
6       forename   0.988063  0.995731  0.991882   2577.0
7       geogName   0.996466  0.988318  0.992375    856.0
8        orgName   0.986600  0.981728  0.984158   2025.0
9       persName   0.983471  0.979424  0.981443    243.0
10     placeName   1.000000  0.986667  0.993289     75.0
11        region   0.974522  0.993506  0.983923    154.0
12    settlement   0.999319  0.999319  0.999319   1468.0
13       surname   0.993548  0.993548  0.993548   2480.0
14          time   0.934579  0.884956  0.909091    113.0
15     micro avg   0.997003  0.996771  0.996887  38713.0
16     macro avg   0.989065  0.973276  0.980635  38713.0
17  weighted avg   0.996995  0.996771  0.996872  38713.0
18   samples avg   0.997941  0.997630  0.997367  38713.0

In [65]:
CRF_final_test = pd.read_csv('/home/jan.solarz/Pobrane/Jan Solarz- Projects/INL/report_test_cff.csv')

In [66]:
report_df(CRF_final_test)

             tag  precision    recall  f1-score  support
0              O   0.999785  1.000000  0.999892  13925.0
1        addName   0.990476  0.971963  0.981132    107.0
2           bloc   1.000000  0.785714  0.880000     14.0
3        country   0.993582  1.000000  0.996780    774.0
4           date   0.995699  0.987207  0.991435    469.0
5       district   1.000000  1.000000  1.000000     34.0
6       forename   0.984957  0.996377  0.990634   1380.0
7       geogName   0.995652  0.984946  0.990270    465.0
8        orgName   0.986085  0.980627  0.983349   1084.0
9       persName   0.976378  0.984127  0.980237    126.0
10     placeName   1.000000  1.000000  1.000000     41.0
11        region   0.989691  0.989691  0.989691     97.0
12    settlement   1.000000  0.998700  0.999349    769.0
13       surname   0.992476  0.993223  0.992849   1328.0
14          time   0.950820  0.920635  0.935484     63.0
15     micro avg   0.996808  0.996953  0.996881  20676.0
16     macro avg   0.990373  0.972881  0.980740  20676.0
17  weighted avg   0.996811  0.996953  0.996868  20676.0
18   samples avg   0.997768  0.997786  0.997336  20676.0

## BERT networks

In [67]:
report_model_base_val = pd.read_csv('/home/jan.solarz/Pobrane/Jan Solarz- Projects/INL/report_model_base_val.csv')

             tag  precision    recall  f1-score        support
0              O   0.994296  0.993091  0.993693  579236.000000
1        addName   0.158433  0.190574  0.173023     488.000000
2           bloc   0.048780  0.061538  0.054422      65.000000
3        country   0.881277  0.913329  0.897017    5169.000000
4           date   0.828289  0.851429  0.839699    1575.000000
5       district   0.155556  0.102941  0.123894     204.000000
6       forename   0.873231  0.891497  0.882270    6645.000000
7       geogName   0.563060  0.532839  0.547533    2832.000000
8        orgName   0.753865  0.754098  0.753982    6466.000000
9       persName   0.571429  0.708688  0.632700     587.000000
10     placeName   0.695067  0.635246  0.663812     244.000000
11        region   0.664418  0.676976  0.670638     582.000000
12    settlement   0.791444  0.822508  0.806677    5758.000000
13       surname   0.846747  0.855866  0.851282    8728.000000
14          time   0.720648  0.674242  0.696673     264.000000
15      accuracy   0.980979  0.980979  0.980979       0.980979
16     macro avg   0.636436  0.644324  0.639154  618843.000000
17  weighted avg   0.981194  0.980979  0.981067  618843.000000

In [70]:
report_model_polish_val = pd.read_csv('/home/jan.solarz/Pobrane/Jan Solarz- Projects/INL/report_model_polish_val.csv')

In [71]:
report_model_polish_val

      Unnamed: 0  precision    recall  f1-score       support
0              O   0.994616  0.993573  0.994094  233541.00000
1            PAD   0.000000  0.000000  0.000000       0.00000
2        addName   0.337539  0.321321  0.329231     333.00000
3           bloc   0.100000  0.173913  0.126984      23.00000
4        country   0.889719  0.907972  0.898753    1706.00000
5           date   0.906459  0.904444  0.905451     900.00000
6       district   0.393939  0.214876  0.278075     121.00000
7       forename   0.869442  0.899679  0.884302    3738.00000
8       geogName   0.682076  0.631381  0.655750    1332.00000
9        orgName   0.794640  0.803986  0.799285    3061.00000
10      persName   0.687050  0.656357  0.671353     291.00000
11     placeName   0.862500  0.575000  0.690000     120.00000
12        region   0.610000  0.578199  0.593674     211.00000
13    settlement   0.826300  0.881675  0.853090    2865.00000
14       surname   0.896062  0.904737  0.900379    5784.00000
15          time   0.787879  0.881356  0.832000     118.00000
16      accuracy   0.981530  0.981530  0.981530       0.98153
17     macro avg   0.664889  0.645529  0.650776  254144.00000
18  weighted avg   0.981514  0.981530  0.981472  254144.00000

## Summary

- CDT: the most simple model shows very weak accuracy, most of the tag's classes have not been recognised at all. The metric macro avg shows the summary of the model which equals 0.11.

- CRF_1: the first approach of CRF already shows a quite good efficiency of this method in these kind of problems in NLP. The prediction on the train sample is almost perfect, all the tag's classes have f1-score around 0.99, tag = 'time' was classified with the lowest recall. Metric macro avg was here 0.98.
In the valid sample the results of the metrics were much more diverse. f1-score in some classes was the value in the range (0.2-0.5), macro avg equaled here **0.68**.

- CRF_final: after CV and hyperparameters optimization the results were much more better, especially on the valid and test samples. Classes "time" and "bloc" had the lowest recalls which implicated to the f1-score. "time" class is of the most complex structures of tag to predict and is complicated, so that is the reason propably. All the 13 other classes had f1-score metric in the range 0.98-1.0 in both samples. On the valid sample macro avg was **0.9968**. **That method of prediction show best way at dealing with the NER issue due to dedicated NLP solutions based on a set of appropriate features included in the learning stage.**

- BERT_basic: the deep learning approach did not bring the expected results, comparing to CRF. The base BERT model on the valid sample had values of f1-score in the range (0.05-0.88). Best result received classes: "forename", "surname" and "country". Comparing on the avarage results also "date" class looks good. Macro avg equals **0.64**

- BERT_polish: analogous to the results of BERT_basic with a bit higher values. Macro avg equals **0.65**. Definietely helped the model based and trained on the polish language corpus. Another disadvantage of BERT approach is time of learning the networks (3-4h vs 0.4h in CRF) and hardware resources.